# Generated by Django 5.2.11 on 2026-02-23 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schematic",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Supprimé"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Référence"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                (
                    "schematic_type",
                    models.CharField(
                        choices=[
                            ("single_line", "Unifilaire"),
                            ("wiring", "Câblage"),
                            ("principle", "Principe"),
                            ("layout", "Implantation"),
                            ("loop", "Boucle"),
                        ],
                        default="single_line",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("review", "En révision"),
                            ("approved", "Approuvé"),
                            ("obsolete", "Obsolète"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="Rev.0", max_length=20, verbose_name="Version"
                    ),
                ),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("NF", "Norme Française (NF)"),
                            ("IEC", "Commission Électrotechnique Internationale (IEC)"),
                            (
                                "IEEE",
                                "Institute of Electrical and Electronics Engineers (IEEE)",
                            ),
                            (
                                "ISO",
                                "Organisation internationale de normalisation (ISO)",
                            ),
                            ("EN", "Norme Européenne (EN)"),
                        ],
                        default="IEC",
                        max_length=10,
                        verbose_name="Norme",
                    ),
                ),
                (
                    "project_ref",
                    models.CharField(
                        blank=True,
                        help_text="Ex: EPR2-PENLY, HPC-HINKLEY",
                        max_length=100,
                        verbose_name="Référence projet",
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True,
                        help_text="Ex: BEP, BK, BR-DDG",
                        max_length=100,
                        verbose_name="Zone / Bâtiment",
                    ),
                ),
                (
                    "page_width",
                    models.FloatField(default=297.0, verbose_name="Largeur page (mm)"),
                ),
                (
                    "page_height",
                    models.FloatField(default=210.0, verbose_name="Hauteur page (mm)"),
                ),
                (
                    "scale",
                    models.CharField(
                        default="1:1", max_length=20, verbose_name="Échelle"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="En révision le"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approuvé le"
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="schematics/sources/",
                        verbose_name="Fichier source (DWG, SVG...)",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_schematics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approuvé par",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schéma électrique",
                "verbose_name_plural": "Schémas électriques",
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="SchematicElement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("circuit_breaker", "Disjoncteur"),
                            ("fuse", "Fusible"),
                            ("contactor", "Contacteur"),
                            ("motor", "Moteur"),
                            ("transformer", "Transformateur"),
                            ("generator", "Générateur"),
                            ("terminal", "Borne"),
                            ("terminal_block", "Bornier"),
                            ("bus", "Jeu de barres"),
                            ("cable", "Câble"),
                            ("sensor", "Capteur"),
                            ("actuator", "Actionneur"),
                            ("lamp", "Voyant / Lampe"),
                            ("switch", "Interrupteur"),
                            ("socket", "Prise de courant"),
                            ("earth", "Terre"),
                            ("text", "Texte"),
                            ("frame", "Cadre"),
                        ],
                        max_length=30,
                        verbose_name="Type d'élément",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 'Q1', 'M-201', 'X1:3'",
                        max_length=100,
                        verbose_name="Étiquette",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Description"
                    ),
                ),
                ("x", models.FloatField(default=0, verbose_name="Position X (mm)")),
                ("y", models.FloatField(default=0, verbose_name="Position Y (mm)")),
                ("width", models.FloatField(default=10, verbose_name="Largeur (mm)")),
                ("height", models.FloatField(default=10, verbose_name="Hauteur (mm)")),
                ("rotation", models.FloatField(default=0, verbose_name="Rotation (°)")),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Ex: {"rating": "16A", "manufacturer": "Schneider"}',
                        verbose_name="Propriétés techniques",
                    ),
                ),
                (
                    "linked_cable_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Câble lié"),
                ),
                (
                    "linked_terminal_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Borne liée"),
                ),
                (
                    "linked_connection_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Raccordement lié"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#000000", max_length=20, verbose_name="Couleur"
                    ),
                ),
                (
                    "font_size",
                    models.FloatField(default=3.0, verbose_name="Taille police (mm)"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Visible"),
                ),
                (
                    "schematic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="schematics.schematic",
                        verbose_name="Schéma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de schéma",
                "verbose_name_plural": "Éléments de schéma",
                "ordering": ["schematic", "y", "x"],
            },
        ),
        migrations.CreateModel(
            name="SchematicLink",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "line_style",
                    models.CharField(
                        choices=[
                            ("solid", "Trait plein"),
                            ("dashed", "Tirets"),
                            ("dotted", "Pointillés"),
                            ("dashdot", "Tiret-point"),
                        ],
                        default="solid",
                        max_length=10,
                        verbose_name="Style de ligne",
                    ),
                ),
                (
                    "line_width",
                    models.FloatField(default=0.5, verbose_name="Épaisseur (mm)"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#000000", max_length=20, verbose_name="Couleur"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Étiquette"
                    ),
                ),
                (
                    "linked_cable_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Câble lié"),
                ),
                (
                    "waypoints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ex: [{"x": 50, "y": 30}, {"x": 50, "y": 80}]',
                        verbose_name="Points de passage",
                    ),
                ),
                (
                    "schematic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="schematics.schematic",
                        verbose_name="Schéma",
                    ),
                ),
                (
                    "source_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_from",
                        to="schematics.schematicelement",
                        verbose_name="Élément source",
                    ),
                ),
                (
                    "target_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_to",
                        to="schematics.schematicelement",
                        verbose_name="Élément cible",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien de schéma",
                "verbose_name_plural": "Liens de schéma",
                "ordering": ["schematic"],
            },
        ),
        migrations.CreateModel(
            name="SchematicRevision",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                ("version", models.CharField(max_length=20, verbose_name="Version")),
                (
                    "description",
                    models.TextField(verbose_name="Description des modifications"),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Snapshot du schéma"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schematic_revisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "schematic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="schematics.schematic",
                        verbose_name="Schéma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Révision de schéma",
                "verbose_name_plural": "Révisions de schémas",
                "ordering": ["schematic", "-created_at"],
                "unique_together": {("schematic", "version")},
            },
        ),
    ]
