# Generated by Django 5.2.11 on 2026-02-23 10:09

import core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Supprimé"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("server", "Serveur"),
                            ("printer", "Imprimante"),
                            ("iot", "Dispositif IoT"),
                            ("switch", "Switch réseau"),
                            ("sensor", "Capteur"),
                            ("controller", "Contrôleur"),
                        ],
                        db_index=True,
                        default="server",
                        max_length=20,
                        verbose_name="Type d'équipement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "En ligne"),
                            ("offline", "Hors ligne"),
                            ("maintenance", "En maintenance"),
                            ("fault", "En défaut"),
                        ],
                        db_index=True,
                        default="online",
                        max_length=20,
                        verbose_name="Statut réseau",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        unique=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[core.validators.validate_mac_address],
                        verbose_name="Adresse MAC",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom d'hôte (hostname)"
                    ),
                ),
                (
                    "vlan",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Numéro du VLAN (1-4094)",
                        null=True,
                        verbose_name="VLAN",
                    ),
                ),
                (
                    "subnet",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 10.0.1.0/24",
                        max_length=20,
                        verbose_name="Sous-réseau",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Dell, Cisco, Schneider Electric",
                        max_length=100,
                        verbose_name="Fabricant",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Modèle"),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Système d'exploitation",
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Version firmware/OS"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Numéro de série"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Salle serveurs B, Rack R3, Unité 12",
                        max_length=300,
                        verbose_name="Localisation",
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bâtiment"
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Salle / Zone"
                    ),
                ),
                (
                    "power_cable_ref",
                    models.CharField(
                        blank=True,
                        help_text="Ex: CAB-EPR-042",
                        max_length=100,
                        verbose_name="Référence câble d'alimentation",
                    ),
                ),
                (
                    "power_supply_voltage",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tension d'alimentation (V)"
                    ),
                ),
                (
                    "power_consumption_w",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Consommation (W)"
                    ),
                ),
                (
                    "is_monitored",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Supervisé"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière vue"
                    ),
                ),
                (
                    "last_scan",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernier scan"
                    ),
                ),
                (
                    "ping_interval_s",
                    models.PositiveIntegerField(
                        default=300, verbose_name="Intervalle de ping (secondes)"
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyen"),
                            ("high", "Élevé"),
                            ("critical", "Critique"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Criticité",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Équipement",
                "verbose_name_plural": "Équipements",
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="DeviceScan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("ping", "Ping (disponibilité)"),
                            ("port_scan", "Scan de ports"),
                            ("vuln_scan", "Scan de vulnérabilités"),
                            ("full", "Scan complet"),
                        ],
                        max_length=15,
                        verbose_name="Type de scan",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Début"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fin"),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Succès"),
                            ("failed", "Échec"),
                            ("partial", "Partiel"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Résultat",
                    ),
                ),
                (
                    "scan_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Données du scan"
                    ),
                ),
                ("ports_found", models.PositiveIntegerField(default=0)),
                ("open_ports_found", models.PositiveIntegerField(default=0)),
                ("unauthorized_ports_found", models.PositiveIntegerField(default=0)),
                ("vulnerabilities_found", models.PositiveIntegerField(default=0)),
                ("critical_vulns_found", models.PositiveIntegerField(default=0)),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="devices.device",
                        verbose_name="Équipement",
                    ),
                ),
                (
                    "launched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Lancé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan de sécurité",
                "verbose_name_plural": "Scans de sécurité",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DevicePort",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "port_number",
                    models.PositiveIntegerField(
                        validators=[core.validators.validate_port_number],
                        verbose_name="Numéro de port",
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[("tcp", "TCP"), ("udp", "UDP"), ("sctp", "SCTP")],
                        default="tcp",
                        max_length=5,
                        verbose_name="Protocole",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("closed", "Fermé"),
                            ("filtered", "Filtré"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="État",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        help_text="Ex: SSH, HTTPS, Modbus, DNP3, IEC-61850",
                        max_length=100,
                        verbose_name="Service",
                    ),
                ),
                (
                    "service_version",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Version du service"
                    ),
                ),
                (
                    "is_authorized",
                    models.BooleanField(
                        default=True,
                        help_text="Port présent dans la liste blanche de sécurité",
                        verbose_name="Autorisé",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Première détection",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Dernière détection",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="devices.device",
                        verbose_name="Équipement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Port réseau",
                "verbose_name_plural": "Ports réseau",
                "ordering": ["device", "port_number"],
                "unique_together": {("device", "port_number", "protocol")},
            },
        ),
        migrations.CreateModel(
            name="DeviceVulnerability",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "cve_id",
                    models.CharField(
                        help_text="Ex: CVE-2024-1234",
                        max_length=20,
                        verbose_name="Identifiant CVE",
                    ),
                ),
                (
                    "cvss_score",
                    models.FloatField(
                        help_text="Score de 0.0 (aucun risque) à 10.0 (critique maximal)",
                        verbose_name="Score CVSS",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Faible (0.0–3.9)"),
                            ("medium", "Moyen (4.0–6.9)"),
                            ("high", "Élevé (7.0–8.9)"),
                            ("critical", "Critique (9.0–10.0)"),
                        ],
                        max_length=10,
                        verbose_name="Sévérité",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "affected_component",
                    models.CharField(
                        blank=True,
                        help_text="Ex: OpenSSL 3.0.x, Windows SMBv1",
                        max_length=200,
                        verbose_name="Composant affecté",
                    ),
                ),
                (
                    "remediation",
                    models.TextField(
                        blank=True,
                        help_text="Patch disponible, contournement, mise à jour...",
                        verbose_name="Action corrective",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouverte"),
                            ("in_progress", "En cours de correction"),
                            ("patched", "Corrigée"),
                            ("accepted", "Risque accepté"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "patched_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Corrigée le"
                    ),
                ),
                (
                    "acceptance_justification",
                    models.TextField(
                        blank=True, verbose_name="Justification acceptation du risque"
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Détectée le"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="devices.device",
                        verbose_name="Équipement",
                    ),
                ),
                (
                    "patched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patched_vulnerabilities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Corrigée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnérabilité",
                "verbose_name_plural": "Vulnérabilités",
                "ordering": ["-cvss_score", "status"],
                "unique_together": {("device", "cve_id")},
            },
        ),
    ]
