# Generated by Django 5.2.11 on 2026-02-23 10:09

import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cable_routing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Terminal",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Ex: 'X1:3', 'L1', 'PE', '+24V'",
                        max_length=50,
                        verbose_name="Étiquette",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Position physique dans le bornier",
                        verbose_name="Position",
                    ),
                ),
                (
                    "terminal_type",
                    models.CharField(
                        choices=[
                            ("screw", "Borne à vis"),
                            ("spring", "Borne à ressort (push-in)"),
                            ("crimp", "Borne à sertir"),
                            ("busbar", "Jeu de barres"),
                        ],
                        default="screw",
                        max_length=20,
                        verbose_name="Type de borne",
                    ),
                ),
                (
                    "max_section_mm2",
                    models.FloatField(
                        validators=[core.validators.validate_cable_section],
                        verbose_name="Section maximale (mm²)",
                    ),
                ),
                (
                    "voltage_rating",
                    models.IntegerField(
                        validators=[core.validators.validate_voltage],
                        verbose_name="Tension nominale (V)",
                    ),
                ),
                (
                    "current_rating",
                    models.FloatField(
                        validators=[core.validators.validate_positive_number],
                        verbose_name="Courant nominal (A)",
                    ),
                ),
                (
                    "recommended_torque_nm",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Couple de serrage recommandé (N·m)",
                    ),
                ),
                (
                    "is_occupied",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Occupée"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Borne",
                "verbose_name_plural": "Bornes",
                "ordering": ["block", "position"],
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Supprimé"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("terminal", "Borne à vis"),
                            ("junction", "Jonction"),
                            ("plug", "Connecteur enfichable"),
                            ("crimp", "Sertissage"),
                            ("weld", "Soudure"),
                        ],
                        default="terminal",
                        max_length=20,
                        verbose_name="Type de raccordement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planifié"),
                            ("in_progress", "En cours"),
                            ("completed", "Réalisé"),
                            ("verified", "Vérifié et conforme"),
                            ("faulty", "Défectueux"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Réalisé le"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vérifié le"
                    ),
                ),
                (
                    "installation_notes",
                    models.TextField(blank=True, verbose_name="Notes d'installation"),
                ),
                (
                    "fault_description",
                    models.TextField(blank=True, verbose_name="Description du défaut"),
                ),
                (
                    "cable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="cable_routing.cable",
                        verbose_name="Câble",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_connections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vérifié par",
                    ),
                ),
                (
                    "terminal_dest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connections_as_dest",
                        to="connections.terminal",
                        verbose_name="Borne destination",
                    ),
                ),
                (
                    "terminal_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connections_as_origin",
                        to="connections.terminal",
                        verbose_name="Borne origine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raccordement",
                "verbose_name_plural": "Raccordements",
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="TerminalBlock",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Supprimé"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Armoire TGBT-A, Rangée 3, Position 2",
                        max_length=200,
                        verbose_name="Localisation",
                    ),
                ),
                (
                    "equipment_ref",
                    models.CharField(
                        blank=True,
                        help_text="Référence de l'armoire ou équipement hôte",
                        max_length=100,
                        verbose_name="Référence équipement",
                    ),
                ),
                (
                    "voltage_rating",
                    models.IntegerField(
                        default=400,
                        validators=[core.validators.validate_voltage],
                        verbose_name="Tension nominale (V)",
                    ),
                ),
                (
                    "current_rating",
                    models.FloatField(
                        default=32.0,
                        validators=[core.validators.validate_positive_number],
                        verbose_name="Courant nominal (A)",
                    ),
                ),
                (
                    "max_section_mm2",
                    models.FloatField(
                        default=16.0,
                        validators=[core.validators.validate_cable_section],
                        verbose_name="Section maximale (mm²)",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Phoenix Contact, Wago, Legrand",
                        max_length=100,
                        verbose_name="Fabricant",
                    ),
                ),
                (
                    "manufacturer_ref",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence fabricant"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bornier",
                "verbose_name_plural": "Borniers",
                "ordering": ["reference"],
            },
        ),
        migrations.AddField(
            model_name="terminal",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terminals",
                to="connections.terminalblock",
                verbose_name="Bornier",
            ),
        ),
        migrations.CreateModel(
            name="ConnectionPoint",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "conductor",
                    models.CharField(
                        choices=[
                            ("L1", "Phase L1"),
                            ("L2", "Phase L2"),
                            ("L3", "Phase L3"),
                            ("N", "Neutre (N)"),
                            ("PE", "Terre (PE)"),
                            ("PEN", "PEN"),
                            ("+", "Positif (+)"),
                            ("-", "Négatif (-)"),
                        ],
                        max_length=5,
                        verbose_name="Conducteur",
                    ),
                ),
                (
                    "wire_color",
                    models.CharField(
                        choices=[
                            ("brown", "Marron (L1)"),
                            ("black", "Noir (L2)"),
                            ("grey", "Gris (L3)"),
                            ("blue", "Bleu (N)"),
                            ("yellow_green", "Vert/Jaune (PE)"),
                            ("red", "Rouge"),
                            ("white", "Blanc"),
                            ("orange", "Orange"),
                        ],
                        max_length=20,
                        verbose_name="Couleur du fil",
                    ),
                ),
                (
                    "tightening_torque_nm",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Couple de serrage réel (N·m)",
                    ),
                ),
                (
                    "has_ferrule",
                    models.BooleanField(
                        default=True, verbose_name="Embout de câblage posé"
                    ),
                ),
                (
                    "ferrule_ref",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Référence embout"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Point vérifié"),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_points",
                        to="connections.connection",
                        verbose_name="Raccordement",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connection_points",
                        to="connections.terminal",
                        verbose_name="Borne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Point de raccordement",
                "verbose_name_plural": "Points de raccordement",
                "ordering": ["connection", "conductor"],
                "unique_together": {("connection", "conductor")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="terminal",
            unique_together={("block", "label")},
        ),
    ]
