# Generated by Django 5.2.11 on 2026-02-23 10:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adresse email"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Prénom"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Nom"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("engineer", "Ingénieur"),
                            ("technician", "Technicien"),
                            ("viewer", "Lecteur"),
                        ],
                        default="viewer",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Compte actif"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Accès admin"),
                ),
                (
                    "mfa_enabled",
                    models.BooleanField(default=False, verbose_name="MFA activé"),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, verbose_name="Email vérifié"),
                ),
                (
                    "failed_login_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tentatives de connexion échouées"
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Compte bloqué jusqu'au"
                    ),
                ),
                (
                    "electrical_certified",
                    models.BooleanField(
                        default=False, verbose_name="Certifié électricité"
                    ),
                ),
                (
                    "certification_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Numéro de certification",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'inscription",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière connexion"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Adresse IP")),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, verbose_name="User Agent (navigateur/OS)"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Localisation approximative",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Session active"),
                ),
                (
                    "logged_out_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Déconnecté le"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session utilisateur",
                "verbose_name_plural": "Sessions utilisateurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MFADevice",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("totp", "Application TOTP (Google Authenticator)"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                        ],
                        default="totp",
                        max_length=10,
                        verbose_name="Type de dispositif",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Mon téléphone",
                        max_length=100,
                        verbose_name="Nom du dispositif",
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(max_length=64, verbose_name="Clé secrète"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Dispositif principal"
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière utilisation"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositif MFA",
                "verbose_name_plural": "Dispositifs MFA",
                "unique_together": {("user", "device_type", "name")},
            },
        ),
    ]
