# Generated by Django 5.2.11 on 2026-02-23 10:09

import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cable",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Supprimé"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planifié"),
                            ("installed", "Installé"),
                            ("active", "Actif"),
                            ("faulty", "Défectueux"),
                            ("decommissioned", "Mis hors service"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "designed_length_m",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[core.validators.validate_cable_length],
                        verbose_name="Longueur prévue (m)",
                    ),
                ),
                (
                    "actual_length_m",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[core.validators.validate_cable_length],
                        verbose_name="Longueur réelle (m)",
                    ),
                ),
                (
                    "origin_label",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Armoire TGBT-A / Disjoncteur Q3",
                        max_length=200,
                        verbose_name="Origine",
                    ),
                ),
                (
                    "destination_label",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Moteur Pompe P-201",
                        max_length=200,
                        verbose_name="Destination",
                    ),
                ),
                (
                    "origin_x",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Origine X (m)"
                    ),
                ),
                (
                    "origin_y",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Origine Y (m)"
                    ),
                ),
                (
                    "origin_z",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Origine Z (m)"
                    ),
                ),
                (
                    "dest_x",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Destination X (m)"
                    ),
                ),
                (
                    "dest_y",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Destination Y (m)"
                    ),
                ),
                (
                    "dest_z",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Destination Z (m)"
                    ),
                ),
                (
                    "design_current_a",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[core.validators.validate_positive_number],
                        verbose_name="Courant de conception (A)",
                    ),
                ),
                (
                    "operating_voltage",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[core.validators.validate_voltage],
                        verbose_name="Tension de service (V)",
                    ),
                ),
                (
                    "installation_notes",
                    models.TextField(blank=True, verbose_name="Notes d'installation"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Câble",
                "verbose_name_plural": "Câbles",
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="CablePathway",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Supprimé"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "pathway_type",
                    models.CharField(
                        choices=[
                            ("cable_tray", "Chemin de câbles"),
                            ("conduit", "Conduit / tube"),
                            ("duct", "Goulotte"),
                            ("trench", "Trémie / fourreau"),
                            ("free_air", "Air libre"),
                        ],
                        default="cable_tray",
                        max_length=20,
                        verbose_name="Type de chemin",
                    ),
                ),
                (
                    "width_mm",
                    models.FloatField(
                        default=200,
                        validators=[core.validators.validate_positive_number],
                        verbose_name="Largeur (mm)",
                    ),
                ),
                (
                    "height_mm",
                    models.FloatField(
                        default=60,
                        validators=[core.validators.validate_positive_number],
                        verbose_name="Hauteur (mm)",
                    ),
                ),
                (
                    "max_fill_ratio",
                    models.FloatField(
                        default=0.4,
                        help_text="Norme IEC : max 40% de remplissage",
                        verbose_name="Taux de remplissage max",
                    ),
                ),
                ("start_x", models.FloatField(default=0, verbose_name="Départ X (m)")),
                ("start_y", models.FloatField(default=0, verbose_name="Départ Y (m)")),
                ("start_z", models.FloatField(default=0, verbose_name="Départ Z (m)")),
                ("end_x", models.FloatField(default=0, verbose_name="Arrivée X (m)")),
                ("end_y", models.FloatField(default=0, verbose_name="Arrivée Y (m)")),
                ("end_z", models.FloatField(default=0, verbose_name="Arrivée Z (m)")),
                (
                    "connected_pathways",
                    models.ManyToManyField(
                        blank=True,
                        to="cable_routing.cablepathway",
                        verbose_name="Pathways connectés",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chemin de câbles",
                "verbose_name_plural": "Chemins de câbles",
            },
        ),
        migrations.CreateModel(
            name="CableRoute",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Tracé actif"),
                ),
                (
                    "is_optimized",
                    models.BooleanField(default=False, verbose_name="Optimisé"),
                ),
                (
                    "total_length_m",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longueur totale (m)"
                    ),
                ),
                (
                    "calculation_notes",
                    models.TextField(blank=True, verbose_name="Notes de calcul"),
                ),
                (
                    "cable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="cable_routing.cable",
                        verbose_name="Câble",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracé de câble",
                "verbose_name_plural": "Tracés de câbles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CableType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Supprimé"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "cable_category",
                    models.CharField(
                        choices=[
                            ("power", "Alimentation"),
                            ("data", "Données"),
                            ("control", "Contrôle"),
                            ("fiber", "Fibre optique"),
                            ("ground", "Terre / Masse"),
                        ],
                        default="power",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "section_mm2",
                    models.FloatField(
                        help_text="Section nominale selon norme IEC (ex: 1.5, 2.5, 6, 16...)",
                        validators=[core.validators.validate_cable_section],
                        verbose_name="Section (mm²)",
                    ),
                ),
                (
                    "voltage_max",
                    models.IntegerField(
                        default=1000,
                        validators=[core.validators.validate_voltage],
                        verbose_name="Tension maximale (V)",
                    ),
                ),
                (
                    "conductor_count",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Ex: 3G6 → 3 conducteurs de 6mm²",
                        verbose_name="Nombre de conducteurs",
                    ),
                ),
                (
                    "conductor_material",
                    models.CharField(
                        choices=[("copper", "Cuivre"), ("aluminum", "Aluminium")],
                        default="copper",
                        max_length=10,
                        verbose_name="Matière conducteur",
                    ),
                ),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("NF", "Norme Française (NF)"),
                            ("IEC", "Commission Électrotechnique Internationale (IEC)"),
                            (
                                "IEEE",
                                "Institute of Electrical and Electronics Engineers (IEEE)",
                            ),
                            (
                                "ISO",
                                "Organisation internationale de normalisation (ISO)",
                            ),
                            ("EN", "Norme Européenne (EN)"),
                        ],
                        default="IEC",
                        max_length=10,
                        verbose_name="Norme",
                    ),
                ),
                (
                    "standard_reference",
                    models.CharField(
                        blank=True,
                        help_text="Ex: IEC 60502-1, NF C 32-102",
                        max_length=50,
                        verbose_name="Référence norme",
                    ),
                ),
                (
                    "outer_diameter_mm",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[core.validators.validate_positive_number],
                        verbose_name="Diamètre extérieur (mm)",
                    ),
                ),
                (
                    "weight_kg_per_m",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[core.validators.validate_positive_number],
                        verbose_name="Masse linéique (kg/m)",
                    ),
                ),
                (
                    "min_bending_radius_mm",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Rayon de courbure minimum (mm)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de câble",
                "verbose_name_plural": "Types de câbles",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="cable",
            name="cable_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cables",
                to="cable_routing.cabletype",
                verbose_name="Type de câble",
            ),
        ),
        migrations.CreateModel(
            name="RouteWaypoint",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Position dans le tracé (1 = départ)",
                        verbose_name="Ordre",
                    ),
                ),
                ("x", models.FloatField(verbose_name="X (m)")),
                ("y", models.FloatField(verbose_name="Y (m)")),
                ("z", models.FloatField(default=0, verbose_name="Z (m)")),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 'Virage armoire A', 'Sortie chemin H1'",
                        max_length=100,
                        verbose_name="Étiquette",
                    ),
                ),
                (
                    "pathway",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waypoints",
                        to="cable_routing.cablepathway",
                        verbose_name="Chemin de câbles",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to="cable_routing.cableroute",
                        verbose_name="Tracé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Point de passage",
                "verbose_name_plural": "Points de passage",
                "ordering": ["route", "order"],
                "unique_together": {("route", "order")},
            },
        ),
    ]
